### ISSUE TITLE
"No such file or directory"

### ISSUE THREAD

**Issue by DFireTech** [dali99/nixos-matrix-modules#8]
Trying to build this module, I get the above

https://pastebin.com/XDthBGu0

This has two excerpts from my `configuration.nix`

Thanks for your help!

**Comment by h7x4** [comment]
Hello @DFireTech, thanks for opening an issue.

I'm missing a bit of information to be able to determine the cause of the problem. However, seeing that you have `ani-cli` installed, I just want to make sure - this is a sort of server machine (or combined server + desktop) which you're trying to set up a matrix server on right? If you're looking for a matrix client, this is the wrong place.

With that said, there's no information about how you've set up the server, or how you're using the module. Maybe you could share the contents of `tgdmatrix.nix`, as long as you censor out the parts you don't want to share or something? Including the logs preceding the "No such file or directory" error or command that resulted in this error would be quite helpful as well.

**Comment by D4ndellion** [comment]
If it helps, the documentation for how to set this up in the readme is a little outdated. If you are not using flakes, the module you should import is probably `nixos-matrix-modules/module.nix` assuming you've cloned the repo as `nixos-matrix-modules`

After that the options should be available for use in your configuration.nix
